added autoconf support for ODBC

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -835,6 +835,9 @@ Optional Packages:
   --with-opengl=DIR root directory path of opengl installation defaults to
                     /usr/local or /usr if not found in /usr/local
   --without-opengl to disable opengl usage completely
+  --with-odbc=DIR root directory path of odbc installation defaults to
+                    /usr/local or /usr if not found in /usr/local
+  --without-odbc to disable odbc usage completely
 
 Some influential environment variables:
   CC          C compiler command
@@ -3128,7 +3131,7 @@ if test -n "${OPENGL_HOME}"
 then
         OPENGL_OLD_LDFLAGS=$LDFLAGS
         OPENGL_OLD_CPPFLAGS=$LDFLAGS
-        LDFLAGS="$LDFLAGS -L${OPENGL_HOME}/lib"
+        LDFLAGS="$LDFLAGS -lm -L${OPENGL_HOME}/lib"
         CPPFLAGS="$CPPFLAGS -I${OPENGL_HOME}/include"
 
 
@@ -3745,6 +3748,315 @@ echo $ECHO_N "checking GL in ${OPENGL_HOME}... $ECHO_C" >&6
 
 	        GL_LDFLAGS=
 
+                echo "$as_me:$LINENO: result: failed" >&5
+echo "${ECHO_T}failed" >&6
+        fi
+fi
+
+
+#
+# Handle user hints
+#
+echo "$as_me:$LINENO: checking if odbc is wanted" >&5
+echo $ECHO_N "checking if odbc is wanted... $ECHO_C" >&6
+
+# Check whether --with-odbc or --without-odbc was given.
+if test "${with_odbc+set}" = set; then
+  withval="$with_odbc"
+  if test "$withval" != no ; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  ODBC_HOME="$withval"
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+else
+
+echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+ODBC_HOME=/usr/local
+if test ! -f "${ODBC_HOME}/include/sqlext.h"
+then
+        ODBC_HOME=/usr
+fi
+
+fi;
+
+#
+# Locate ODBC, if wanted
+#
+if test -n "${ODBC_HOME}"
+then
+        ODBC_OLD_LDFLAGS=$LDFLAGS
+        ODBC_OLD_CPPFLAGS=$LDFLAGS
+        LDFLAGS="$LDFLAGS -L${ODBC_HOME}/lib"
+        CPPFLAGS="$CPPFLAGS -I${ODBC_HOME}/include"
+
+
+        ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+        echo "$as_me:$LINENO: checking for SQLAllocConnect in -liodbc" >&5
+echo $ECHO_N "checking for SQLAllocConnect in -liodbc... $ECHO_C" >&6
+if test "${ac_cv_lib_iodbc_SQLAllocConnect+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-liodbc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SQLAllocConnect ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+SQLAllocConnect ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_iodbc_SQLAllocConnect=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_iodbc_SQLAllocConnect=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_iodbc_SQLAllocConnect" >&5
+echo "${ECHO_T}$ac_cv_lib_iodbc_SQLAllocConnect" >&6
+if test $ac_cv_lib_iodbc_SQLAllocConnect = yes; then
+  odbc_cv_libiodbc=yes
+else
+  odbc_cv_libiodbc=no
+fi
+
+        if test "${ac_cv_header_sqlext_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for sqlext.h" >&5
+echo $ECHO_N "checking for sqlext.h... $ECHO_C" >&6
+if test "${ac_cv_header_sqlext_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sqlext_h" >&5
+echo "${ECHO_T}$ac_cv_header_sqlext_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking sqlext.h usability" >&5
+echo $ECHO_N "checking sqlext.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <sqlext.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking sqlext.h presence" >&5
+echo $ECHO_N "checking sqlext.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <sqlext.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: sqlext.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: sqlext.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sqlext.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: sqlext.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: sqlext.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: sqlext.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sqlext.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: sqlext.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sqlext.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: sqlext.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for sqlext.h" >&5
+echo $ECHO_N "checking for sqlext.h... $ECHO_C" >&6
+if test "${ac_cv_header_sqlext_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_sqlext_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sqlext_h" >&5
+echo "${ECHO_T}$ac_cv_header_sqlext_h" >&6
+
+fi
+if test $ac_cv_header_sqlext_h = yes; then
+  odbc_cv_sqlext_h=yes
+else
+  odbc_cv_sqlext_h=no
+fi
+
+
+        ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+        if test "$odbc_cv_libiodbc" = "yes" -a "$odbc_cv_sqlext_h" = "yes"
+        then
+                #
+                # If both library and headers were found, use them
+                #
+
+echo "$as_me:$LINENO: checking for SQLAllocConnect in -liodbc" >&5
+echo $ECHO_N "checking for SQLAllocConnect in -liodbc... $ECHO_C" >&6
+if test "${ac_cv_lib_iodbc_SQLAllocConnect+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-liodbc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SQLAllocConnect ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+SQLAllocConnect ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_iodbc_SQLAllocConnect=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_iodbc_SQLAllocConnect=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_iodbc_SQLAllocConnect" >&5
+echo "${ECHO_T}$ac_cv_lib_iodbc_SQLAllocConnect" >&6
+if test $ac_cv_lib_iodbc_SQLAllocConnect = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBIODBC 1
+_ACEOF
+
+  LIBS="-liodbc $LIBS"
+
+fi
+
+                echo "$as_me:$LINENO: checking odbc in ${ODBC_HOME}" >&5
+echo $ECHO_N "checking odbc in ${ODBC_HOME}... $ECHO_C" >&6
+                echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
+        else
+                #
+                # If either header or library was not found, revert and bomb
+                #
+                echo "$as_me:$LINENO: checking odbc in ${ODBC_HOME}" >&5
+echo $ECHO_N "checking odbc in ${ODBC_HOME}... $ECHO_C" >&6
+                LDFLAGS="$ODBC_OLD_LDFLAGS"
+                CPPFLAGS="$ODBC_OLD_CPPFLAGS"
                 echo "$as_me:$LINENO: result: failed" >&5
 echo "${ECHO_T}failed" >&6
         fi
