tests: re-enable some Windows special cases
Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

diff --git a/tests/Makefile.test b/tests/Makefile.test
--- a/tests/Makefile.test
+++ b/tests/Makefile.test
@@ -29,7 +29,7 @@ $(IGNORE):
 	else ./$@ > local/$@.out 2>&1; fi || true
 	-@echo "Expect/ignore these differences in $@:"
 	-@diff stand/$@.std local/$@.out; \
-	if [ $$? -eq 0 ] ; then echo "OK"; \
+	@if [ $$? -eq 0 ] ; then echo "OK"; \
 	else echo "[Test $@] Ignored"; fi || true
 	-@rm $@$(EXE)
 
@@ -56,10 +56,16 @@ endif
 	@if [ -f data/$@.dat ] ; then \
 	./$@ < data/$@.dat  > local/$@.out 2>&1; \
 	else ./$@ > local/$@.out 2>&1; fi || true
-	-@diff -wq stand/$@.std local/$@.out >/dev/null; \
+	@if [ x$(EXE) = x.exe ] && [ -f stand/$@.wstd ] ; then \
+	diff -wq stand/$@.wstd local/$@.out >/dev/null; \
+	if [ $$? -eq 0 ] ; then echo "W OK"; \
+	else echo "W Failed"; \
+	diff --suppress-common-lines -wy stand/$@.wstd local/$@.out > $@.diff; fi \
+	else diff -wq stand/$@.std local/$@.out >/dev/null; \
 	if [ $$? -eq 0 ] ; then echo "OK"; \
 	else echo "Failed"; \
-	diff --suppress-common-lines -wy stand/$@.std local/$@.out > $@.diff; fi || true
+	diff --suppress-common-lines -wy stand/$@.std local/$@.out > $@.diff; fi \
+	fi || true
 	-@rm $@$(EXE)
 
 FILES=$(patsubst %.diff,%.report,$(wildcard *.diff))
