tests/coexpr/Makefile: add grep...|diff... target

diff --git a/tests/coexpr/Makefile b/tests/coexpr/Makefile
--- a/tests/coexpr/Makefile
+++ b/tests/coexpr/Makefile
@@ -1,48 +1,73 @@
 #  Makefile for testing Unicon coexpressions
 
+BIN=../../bin
 include ../Makedefs
 
+ifdef Verbose
+TEE=tee
+else
 TEE=cat - > 
+endif
+
 # 
 # for verbose progress, run as:
 # make verbose
 # or 
-# TEE=tee make -e [target ...]
+# Verbose=1 make -e [target ...]
 #
 
 DIFFTST = moveco
-GREPTST = cobench stressCo stressCollectCo
+GREPTST = cobench stressCo 
+GREPDIFFTST = stressCollectCo
 #TARGETS=$(patsubst %.icn,%,$(wildcard *.icn))
 #IGNORE=$(COTST)
 # ^ skipped. 
-TARGETS= $(DIFFTST) $(GREPTST) 
+TARGETS= $(DIFFTST) $(GREPTST) $(GREPDIFFTST)
 
 # Do the tests
 Test: DoTest
 
 Uniconc : 
-	SKIP=moveco TEE=tee UC="../../bin/unicon -C " make -e Test
+	SKIP=moveco Verbose=1 UC="$(UCC)" make -e Test
 #  moveco does coexpr(), not supported by iconc yet, skip. 
 
 
 ${GREPTST} : % : %.icn local stand/%.std
 	-@$E -n "[Testing $@]... "
 	@$(UC) $(UFLAGS) $<
-	./$@ | $(TEE) local/$@.out
+	-./$@ | $(TEE) local/$@.out
 	-@grep -f stand/$@.std local/$@.out >/dev/null; \
 	if [ $$? -eq 0 ] ; then echo "OK"; \
-	else echo "Failed"; diff -wy stand/$@.std local/$@.out > $@.diff; fi || true
+	else echo "$@ Failed"; diff -wy stand/$@.std local/$@.out > $@.diff; fi || true
 	-@rm -f $@$(EXE)
+# ALERT: this will pass if ANY lines in .std match ANY part of any line in .out
+# use GREPDIFFTST for a stricter match
+
+${GREPDIFFTST} : % : %.icn local stand/%.std stand/%.grep
+	-@$E -n "[Testing $@]... "
+	@$(UC) $(UFLAGS) $<
+	-./$@ | $(TEE) local/$@.out
+	-@grep -f stand/$@.grep local/$@.out | diff stand/$@.std - > /dev/null ; \
+	if [ $$? -eq 0 ] ; then echo "OK"; \
+	else echo "$@ Failed"; \
+	grep -f stand/$@.grep local/$@.out | diff -wy stand/$@.std - > $@.diff; \
+	fi || true
+	-@rm -f $@$(EXE)
+# This will pass if all lines of .out with ANY part matching any line in .grep match .std 
 
 
 include ../Makefile.test
 
-Icont Test-icont :
-		IC=unicon sh Test-icon $(COTST)
+#icont Icont Test-icont :
+#	SKIP=stressCollectCo IC=$(BIN)/icont sh Test-icon $(COTST)
 
-Iconc Test-iconc :
-		IC="unicon -C " sh Test-icon $(COTST)
+icont Icont : 
+	SKIP=stressCollectCo UC="$(BIN)/icont" make -e Test
+
+iconc Iconc : 
+	SKIP="moveco stressCollectCo" Verbose=1 UC="$(BIN)/iconc" make -e Test
+#  moveco does coexpr(), not supported by iconc yet, skip. 
 
 verbose: 
-	TEE=tee $(MAKE) -e
+	Verbose=1 $(MAKE) -e
 
