udb: Fix udb Makefile and use unicon_for_tests in adapter test
Signed-off-by: Joseph Abdo <josephabdo200@gmail.com>

diff --git a/tests/udb/Makefile b/tests/udb/Makefile
--- a/tests/udb/Makefile
+++ b/tests/udb/Makefile
@@ -1,21 +1,51 @@
 include ../Makedefs
 
 TESTNAME=udb
-UDB=../../bin/udb --line
 
-UDBTARGETS=basic print breakpoints watchpoints counter_line counter_syntax \
-	counter_deref counter_pcall coexp scoping
-TARGETS=$(UDBTARGETS) adapter
-CLEAN_EXTRA=watchme printme prime scopes test_adapter data/test_target
+TARGETS=basic print breakpoints watchpoints counter_line counter_syntax \
+	counter_deref counter_pcall coexp scoping adapter
 
 Test: DoTest
 
 include ../Makefile.test
 
-basic watchpoints counter_line counter_syntax counter_deref counter_pcall: PROG=watchme
-print: PROG=printme
-breakpoints coexp: PROG=prime
-scoping: PROG=scopes
+define check_output
+	@tr -d '\r' < local/$@.out > local/$@.nr; \
+	if [ x$(EXE) = x.exe ] && [ -f stand/$@.wstd ] ; then \
+	diff -wq stand/$@.wstd local/$@.nr >/dev/null; \
+	if [ $$? -eq 0 ] ; then echo "w pass"; \
+	else echo "w FAIL"; \
+	diff --suppress-common-lines -wy stand/$@.wstd local/$@.nr > $@.diff; fi \
+	else \
+	diff -wq stand/$@.std local/$@.nr >/dev/null; \
+	if [ $$? -eq 0 ] ; then echo "pass"; \
+	else \
+	if grep -qi "This Program Requires" local/$@.out; then cat local/$@.out; \
+	else echo "FAIL"; \
+	diff --suppress-common-lines -wy stand/$@.std local/$@.nr > $@.diff; fi \
+	fi; \
+	fi || true
+endef
+
+basic watchpoints counter_line counter_syntax counter_deref counter_pcall: %: local stand/%.std input/%.udb watchme
+	-@$E -n "[Testing $@]... "
+	@../../bin/udb --line watchme < input/$@.udb > local/$@.out 2>&1 || true
+	$(check_output)
+
+print: %: local stand/%.std input/%.udb printme
+	-@$E -n "[Testing $@]... "
+	@../../bin/udb --line printme < input/$@.udb > local/$@.out 2>&1 || true
+	$(check_output)
+
+breakpoints coexp: %: local stand/%.std input/%.udb prime
+	-@$E -n "[Testing $@]... "
+	@../../bin/udb --line prime < input/$@.udb > local/$@.out 2>&1 || true
+	$(check_output)
+
+scoping: %: local stand/%.std input/%.udb scopes
+	-@$E -n "[Testing $@]... "
+	@../../bin/udb --line scopes < input/$@.udb > local/$@.out 2>&1 || true
+	$(check_output)
 
 watchme: watchme.icn
 	@$(UC) $(UFLAGS) $< > /dev/null 2>&1
@@ -29,23 +59,13 @@ prime: foo.icn prime.icn
 scopes: scopepkg.icn scopes.icn
 	@$(UC) $(UFLAGS) -o $@ $^ > /dev/null 2>&1
 
+test_adapter: adapter.icn
+	@$(UC) $(UFLAGS) $< -o $@ > /dev/null 2>&1
+
 data/test_target: data/test_target.icn
 	@$(UC) $(UFLAGS) -o $@ $< > /dev/null 2>&1
 
-adapter: local stand/adapter.std data/test_target
+adapter: local stand/adapter.std data/test_target test_adapter
 	-@$E -n "[Testing $@]... "
-	@$(UC) $(UFLAGS) adapter.icn -o test_adapter > /dev/null 2>&1
 	@./test_adapter > local/$@.out 2>&1 || true
-	@if [ x$(EXE) = x.exe ] && [ -f stand/$@.wstd ] ; then \
-	diff -wq stand/$@.wstd local/$@.out >/dev/null; \
-	if [ $$? -eq 0 ] ; then echo "w pass"; \
-	else echo "w FAIL"; \
-	diff --suppress-common-lines -wy stand/$@.wstd local/$@.out > $@.diff; fi \
-	else diff -wq stand/$@.std local/$@.out >/dev/null; \
-	if [ $$? -eq 0 ] ; then echo "pass"; \
-	else \
-	if grep -qi "This Program Requires" local/$@.out; then cat local/$@.out; \
-	else echo "FAIL"; \
-	diff --suppress-common-lines -wy stand/$@.std local/$@.out > $@.diff; fi \
-	fi; \
-	fi || true
+	$(check_output)
